services:
  express:
    build:
      context: ./node-js/express
    container_name: express
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
    ports:
      - "3000:3000"

  fastify:
    build:
      context: ./node-js/fastify
    container_name: fastify
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
    ports:
      - "3001:3000"

  jaxrs:
    build: 
      context: ./jakarta-ee/jaxrs
    container_name: jaxrs
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
    ports: 
      - "3002:9080"

  httpservlet:
    build: 
      context: ./jakarta-ee/httpservlet
    container_name: httpservlet
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
    ports: 
      - "3003:9080"